[workspace]
members = [
    "lib",
    "program",
    "script",
    "contracts"
]
resolver = "2"

[workspace.dependencies]
alloy-sol-types = "1.1.0"
alloy-primitives = "1.2.1"
serde = { version = "1.0.200", default-features = false, features = ["derive"] }