services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb
    environment:
      - POSTGRES_DB=m3tering-db
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-m3tering}
    expose:
      - 5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      
  streamr-client:
    image: ghcr.io/m3tering/prover/streamr-client:main
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:m3tering@db:5432/m3tering-db}
      - STREAM_ID=${STREAM_ID}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - STREAMR_ENV=${STREAMR_ENV:-live}
    depends_on:
      db:
        condition: service_healthy

  energy-tracker:
    image: ghcr.io/m3tering/prover:main
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - DATABASE_URL=${DATABASE_URL:-postgres://postgres:m3tering@db:5432/m3tering-db}
      - NETWORK_RPC_URL=${NETWORK_RPC_URL:-https://rpc.mainnet.succinct.xyz}
      - RPC_URL=${RPC_URL:-https://eth-sepolia.g.alchemy.com/v2/URjQnzNCUHumxPFL8VDoFBmpX4uqL6X8}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - BLOCK_INTERVAL=${BLOCK_INTERVAL}
      - DATA_STRATEGY=${DATA_STRATEGY:-delete}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:
